name = "MyTheme"
license = "MIT"
licenselink = "https://github.com/carlosrabelo/carlosrabelo.com.br/blob/master/themes/mytheme/LICENSE"
description = "A custom minimal Hugo blog theme (Maverick/Ink inspired)"

# The home page of the theme, where the source can be found.
homepage = "https://carlosrabelo.com.br/"

# If you have a running demo of the theme.
demosite = "https://carlosrabelo.com.br/"

tags = ["blog", "minimal", "custom"]
features = ["minimal", "fast", "responsive"]

# If the theme has a single author
[author]
    name = "Carlos Rabelo"
    homepage = "https://carlosrabelo.com.br/"

[original]
    name = "Calvin Tran"
    homepage = "https://github.com/knadh"
